# Generated by Django 4.2.5 on 2023-10-08 06:43

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image Point of Interest')),
                ('thumbnail', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/thumbnails/')),
                ('medium', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/medium/')),
                ('large', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images/large/')),
            ],
        ),
    ]
